// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MapConfig } from "./tables/MapConfig.sol";
import { Movable } from "./tables/Movable.sol";
import { Slippery } from "./tables/Slippery.sol";
import { Obstruction } from "./tables/Obstruction.sol";
import { OwnedBy } from "./tables/OwnedBy.sol";
import { Player } from "./tables/Player.sol";
import { Position } from "./tables/Position.sol";
